completed css-fonts
m-Cho1/lfz-alumni-code-solutions pull request #14
Opened 2022-10-31 23:47 UTC by m-Cho1

![image](https://user-images.githubusercontent.com/96744088/199130051-7a499c6f-c491-437d-a8bd-31a9cbfd886b.png)

2022-11-01 14:15 UTC, thebearingedge requested changes

2022-11-01 14:15 UTC, thebearingedge commented on css-fonts/index.html
> +  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
You can remove lines 11 and 12 since you already set up the preconnect on lines 8 and 9

2022-11-01 22:03 UTC, m-Cho1 commented
Removed extra link tags

2022-11-10 18:44 UTC, thebearingedge approved these changes

2022-11-11 09:53 UTC, merged