completed css-brochure-form
m-Cho1/lfz-alumni-code-solutions pull request #15
Opened 2022-11-01 06:32 UTC by m-Cho1

![image](https://user-images.githubusercontent.com/96744088/199173230-499a461c-c576-4da8-837a-f84191b8df69.png)

2022-11-01 14:16 UTC, thebearingedge requested changes

2022-11-01 14:16 UTC, thebearingedge commented on css-brochure-form/index.html
> +  <link href="https://fonts.googleapis.com/css2?family=Nunito&display=swap" rel="stylesheet">
If I'm not mistaken, you can remove these and use the supplied fonts.

2022-11-01 22:07 UTC, m-Cho1 commented
![image](https://user-images.githubusercontent.com/96744088/199351193-2f0ff50b-cd52-43ae-81ad-3bed7ffa7bf8.png)

Switched fonts

2022-11-10 18:44 UTC, thebearingedge approved these changes

2022-11-11 09:53 UTC, merged