completed css-positioning
m-Cho1/lfz-alumni-code-solutions pull request #19
Opened 2022-11-03 13:10 UTC by m-Cho1

relative-positioning:
![image](https://user-images.githubusercontent.com/96744088/199729048-56ad13ca-4172-4fc7-97b4-65e6861dd538.png)

absolute positioning:
![image](https://user-images.githubusercontent.com/96744088/199729185-79232f0a-f355-4326-87b9-897a22859ee0.png)

fixed positioning:
![image](https://user-images.githubusercontent.com/96744088/199729240-6ebaaf88-ead5-4a11-8c45-a1a154395806.png)

2022-11-10 18:46 UTC, thebearingedge requested changes

2022-11-10 18:46 UTC, thebearingedge commented on css-positioning/absolute.css
> +  left: 14rem;
Instead of doing really huge box offsets, try switching to `position: absolute` and use offsets from the sides you want to be close to.

2022-11-10 18:46 UTC, thebearingedge commented on css-positioning/absolute.css
> +  bottom: 9rem;
here too

2022-11-11 10:00 UTC, m-Cho1 commented
Edited position properties and values: 
![image](https://user-images.githubusercontent.com/96744088/201316086-9e4e07d5-0c91-4e96-bbaa-6f79b46ce40a.png)

2022-11-13 22:48 UTC, thebearingedge approved these changes

2022-11-15 01:16 UTC, merged