completed css-transitions
m-Cho1/lfz-alumni-code-solutions pull request #22
Opened 2022-11-04 03:33 UTC by m-Cho1

![css-transitions](https://user-images.githubusercontent.com/96744088/199879533-85aa4448-7456-4565-808d-e1b91cba4f1d.gif)

2022-11-10 19:30 UTC, thebearingedge requested changes

2022-11-10 19:30 UTC, thebearingedge commented on css-transitions/styles.css
> +  transition: 0.5s;
Be sure to specify which CSS properties you want to transition. the default is `all`, which can be very computationally expensive.

https://developer.mozilla.org/en-US/docs/Web/CSS/transition#syntax

2022-11-11 10:06 UTC, m-Cho1 commented
Edited transition properties
![image](https://user-images.githubusercontent.com/96744088/201317224-48c57be0-8a62-4046-99a5-fdfa283b253b.png)

2022-11-13 22:49 UTC, thebearingedge approved these changes

2022-11-15 01:16 UTC, merged