completed javascript-data-model
m-Cho1/lfz-alumni-code-solutions pull request #29
Opened 2022-11-05 12:04 UTC by m-Cho1

![image](https://user-images.githubusercontent.com/96744088/200118974-d99579f2-17e0-487a-a668-d1a81e64baf1.png)

2022-11-10 19:34 UTC, thebearingedge requested changes

2022-11-10 19:34 UTC, thebearingedge commented on javascript-data-model/order-history.js
> +    ],
Since order information never seems to have more than one object in it, we can just make it an object instead of an array.

2022-11-11 10:14 UTC, m-Cho1 commented
Edited javascript-data-model

2022-11-13 22:49 UTC, thebearingedge approved these changes

2022-11-15 01:15 UTC, merged