completed javascript-loops-practice
m-Cho1/lfz-alumni-code-solutions pull request #35
Opened 2022-11-06 09:09 UTC by m-Cho1

![image](https://user-images.githubusercontent.com/96744088/200162772-6e4dc029-6e69-4b38-b135-6d956d8fc96c.png)

2022-11-06 09:17 UTC, m-Cho1 commented
moved codes to correct js files

2022-11-10 19:39 UTC, thebearingedge requested changes

2022-11-10 19:39 UTC, thebearingedge commented on javascript-loops-practice/filter-out-strings.js
> +    }
Here it would be safer to exclude strings (filter out strings) instead of add numbers.

2022-11-11 10:18 UTC, m-Cho1 commented
edited javascript-loops-practice
![image](https://user-images.githubusercontent.com/96744088/201319397-c3e3bac7-13af-4581-878b-e041b99d5739.png)

2022-11-13 22:50 UTC, thebearingedge approved these changes

2022-11-15 01:15 UTC, merged